### ISSUE TITLE
No framer found for TinkerVertex with label vertex

### ISSUE THREAD

**Issue by mohataher** [bayofmany/peapod#2]
I get this error everytime I try to run the example 
https://github.com/bayofmany/peapod/blob/master/demo/src/test/java/peapod/demo/classic/ShowcaseClassicTest.java

I tried to take all these classes in a totally new project. And I get the same error. I don't know if this is a library error or a mistake I'm making.

Error:
```
java.lang.RuntimeException: No framer found for TinkerVertex with label vertex
	at peapod.internal.runtime.FramerRegistry.get(FramerRegistry.java:81)
	at peapod.FramedGraph.frame(FramedGraph.java:138)
	at peapod.FramedGraph.v(FramedGraph.java:129)
	at com.mohataher.peapod.test.ShowcaseClassicTest.init(ShowcaseClassicTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

pom.xml (FYI) 
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mohataher</groupId>
	<artifactId>peapod-test</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>2.8.2</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>

		<dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>gremlin-core</artifactId>
			<version>3.0.0.M9-incubating</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>tinkergraph-gremlin</artifactId>
			<version>3.0.0.M9-incubating</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.bayofmany.peapod</groupId>
			<artifactId>peapod</artifactId>
			<version>0.2.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>java-hamcrest</artifactId>
			<version>2.0.0.0</version>
			<scope>test</scope>
		</dependency>


	</dependencies>
</project>
```

**Comment by bayofmany** [comment]
Hello @mohataher,

I couldn't reproduce your case. Can you send your maven output please to help debugging?

- Do you launch the testcase with maven or in an IDE?
- Do you see any classes generated in \target\generated-sources\annotations?
- When running from an IDE, is the generated folder recognized as an additional source folder?


```
C:\tmp\test>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building peapod-test 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ peapod-test ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\tmp\test\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ peapod-test ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 10 source files to C:\tmp\test\target\classes
[WARNING] /C:/tmp/test/target/generated-sources/annotations/peapod/demo/vertexproperty/Name$Impl.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/tmp/test/target/generated-sources/annotations/peapod/demo/vertexproperty/Name$Impl.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ peapod-test ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\tmp\test\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ peapod-test ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 3 source files to C:\tmp\test\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ peapod-test ---
[INFO] Surefire report directory: C:\tmp\test\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running peapod.demo.classic.ShowcaseClassicTest
log4j:WARN No appenders could be found for logger (org.reflections.Reflections).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.46 sec
Running peapod.demo.crew.ShowcaseCrewTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec
Running peapod.demo.vertexproperty.VertexPropertyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec

Results :

Tests run: 7, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ peapod-test ---
[INFO] Building jar: C:\tmp\test\target\peapod-test-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ peapod-test ---
[INFO] Installing C:\tmp\test\target\peapod-test-0.0.1-SNAPSHOT.jar to C:\Users\Willem\.m2\repository\com\mohataher\peapod-test\0.0.1-SNAPSHOT\peapod-test-0.0.1-SNAPSHOT.jar
[INFO] Installing C:\tmp\test\pom.xml to C:\Users\Willem\.m2\repository\com\mohataher\peapod-test\0.0.1-SNAPSHOT\peapod-test-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.961 s
[INFO] Finished at: 2015-06-25T19:51:34+02:00
[INFO] Final Memory: 21M/308M
[INFO] ------------------------------------------------------------------------
```

**Comment by mohataher** [comment]
It seems like there is a problem with the annotation processor.  Shouldn't this work out-of-the-box?

Here is the output. 
```
$ mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building peapod-test 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ peapod-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ peapod-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-processor-plugin:2.2.4:process-test (process-test) @ peapod-test ---
[WARNING] No processors specified. Using default discovery mechanism.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ peapod-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ peapod-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ peapod-test ---
[INFO] Surefire report directory: C:\Users\bsmtaa\eclipse_kapsoft\peapod-test\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsupportedClassVersionError: com/mohataher/peapod/test/ShowcaseClassicTest : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
        at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
        at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
        ... 9 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.672 s
[INFO] Finished at: 2015-06-25T23:40:47+01:00
[INFO] Final Memory: 17M/227M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project peapod-test: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException


```

**Comment by mohataher** [comment]
I finally got this to run. I will try to document all my steps just in case someone got stuck like me.

First, I installed "m2e-apt" from Eclipse Marketplace
Second, I configured the project to allow annotation processing.
Follow this tutorial, https://immutables.github.io/apt.html
Finally, this is how my pom.xml that works look like
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.mohataher</groupId>
	<artifactId>peapod-test</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>


	<build>
		<plugins>
			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>maven-processor-plugin</artifactId>
				<version>2.2.4</version>
				<executions>
					<execution>
						<id>process-test</id>
						<goals>
							<goal>process-test</goal>
						</goals>
						<phase>generate-test-sources</phase>
						<configuration>
							<outputDirectory>${project.build.directory}/generated-test-sources/test-annotations
							</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>

				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
				
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.5</version>
				<executions>
					<execution>
						<goals>
							<goal>test-jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>gremlin-core</artifactId>
			<version>3.0.0.M9-incubating</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tinkerpop</groupId>
			<artifactId>tinkergraph-gremlin</artifactId>
			<version>3.0.0.M9-incubating</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.bayofmany.peapod</groupId>
			<artifactId>peapod</artifactId>
			<version>0.2.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>java-hamcrest</artifactId>
			<version>2.0.0.0</version>
			<scope>test</scope>
		</dependency>


	</dependencies>
</project>
```

**Comment by bayofmany** [comment]
There is no need to define the maven-processor-plugin in your pom file. It works with your original pom.xml too.

I just installed Eclipse Mars Java EE with m2e-apt plugin. Then in Preferences > Maven > Annotation processing, choose 'Automatically configure JDT APT'.

Thanks for your feedback.

**Comment by mohataher** [comment]
Sorry to come up again but I tried to import and get peapod project to run on eclipse (to edit some code and possibly submit a pull request later on) and I tried to do this for more thna 4 hours with no success. The annotation processor never fires. I even used a fresh Eclipse Mars to do it and I got no success.

If you are keen to get others into the project, would it be possible to try to checkout and import the whole project on a clean new workspace and document all the steps and share it here or on the wiki? That would be really helpful.

**Comment by bayofmany** [comment]
My steps:

- Clean ubuntu-14.04.2 virtualbox vm
- Clean install eclipse-jee-mars-R-linux-gtk-x86_64.tar.gz with empty workspace
- Via eclipse marketplace install m2e-apt 1.1.1
- Eclipse preferences > Maven > Annotation processing, choose 'Automatically configure JDT APT'.
- Import existing maven project and run tests.

With this config target/generated-sources/annotations is automatically recognized as source folder.

Maven 3.3.3
Java 8u45
